apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: $BACKEND_IMAGE_URL
          ports:
            - containerPort: $BACKEND_PORT
          env:
            - name: POSTGRES_HOST
              value: $POSTGRES_HOST
            - name: POSTGRES_PORT
              value: $POSTGRES_PORT
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
            - name: AWS_S3_BUCKET_NAME
              value: $AWS_S3_BUCKET_NAME
            - name: AWS_ACCESS_KEY
              value: $AWS_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              value: $AWS_SECRET_ACCESS_KEY
