# This isn't used yet; this is for Helm migration stuff later
api:
  replicaCount: 2
  image: 370056820766.dkr.ecr.us-east-1.amazonaws.com/tinynakji-backend:latest
  port: 5000
  env:
    POSTGRES_HOST: "localhost"
    POSTGRES_PORT: 5432
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "myuser"
    POSTGRES_PASSWORD: "mypassword"
    AWS_S3_BUCKET_NAME: "my-bucket"
    AWS_ACCESS_KEY: "my-access-key"
    AWS_SECRET_ACCESS_KEY: "my-secret-access-key"
