"""Add image url to user tables

Revision ID: 980ca2bc16d0
Revises: 0ebce3935741
Create Date: 2023-02-11 19:28:02.240242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980ca2bc16d0'
down_revision = '0ebce3935741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
