apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: ui
  ports:
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: http-server
    - name: https
      protocol: TCP
      port: 443
      targetPort: $FRONTEND_PORT
    - name: http
      protocol: TCP
      port: 80
      targetPort: $FRONTEND_PORT
  type: ClusterIP
